### ISSUE TITLE
Add more experiments

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-NRI/experiment-metadb#1]
It would be good to make some more experiments available through the prototype interface.

Obvious candidates would be ones we definitely want to have available in the long term from this forum topic

https://forum.access-hive.org.au/t/access-om2-control-runs/258

1. `01deg_jra55v140_iaf_cycle4`
2. `025deg_jra55_ryf9091_gadi`
3. `025deg_jra55_iaf_omip2_cycle6`
4. `1deg_jra55_ryf9091_gadi`
5. `1deg_jra55_iaf_omip2_cycle6`

**Comment by utkarshgupta95** [comment]
these experiments are added now
