### ISSUE TITLE
Add fields for `spack-packages` version and `spack-config` version to the `model` table

### ISSUE THREAD

**Issue by CodeGat** [ACCESS-NRI/experiment-metadb#15]
Currently, we have a lot of metadata about the build, but we don't know about versions of `spack-packages` and `spack-config` that are used to deploy the build. 

Could we add these fields to the metadata DB JSON and the DB itself? I think it'd be a couple of fields on the model, nullable strings probably. 

The version strings look like `2024.02.23` for example.

**Comment by utkarshgupta95** [comment]
@CodeGat are these versions different from the one in this table https://experiment-metadb-seven.vercel.app/release-provenance

**Comment by CodeGat** [comment]
Yeah. Those are versions of models or model components. They are of the form `YYYY.MM.MINOR`.

`spack-packages` and `spack-config` are repositories at ACCESS-NRI for the configuration of spack and its packages, unrelated to model code. They are of the form `YYYY.MM.DD`.
