### ISSUE TITLE
Add tables to capture build provenance

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-NRI/experiment-metadb#8]
There is a need to link the provenance of a build to the provenance of an experiment that uses that build.

The key that would allow for this is the `md5` hash in the `exe.yaml` manifest. 

Maybe a schema something like this (this is DBML)

```sql
Table componentbuilds {
  spackhash varchar [primary key] // ewcdbrfukblyjxpkhd3mfkj4yxfolal4
  spec varchar // mom5@git.2023.11.09=2023.11.09
  modelbuildhash varchar [ref: > modelbuilds.spackhash] // f4f2qe5b3c22q4dtzzqs5o2iygy435re
  installpath varchar // /g/data/vk83/apps/spack/0.20/release/linux-rocky8-x86_64/intel-19.0.5.281/
  md5 varchar // 2432c23048525b384fd57e8cd2ed7e3b
  created_at timestamp // 00:00:00-09222023
  release_url url // https://github.com/ACCESS-NRI/ACCESS-OM2/releases
}

Table modelbuilds { 
  spackhash varchar [primary key] // f4f2qe5b3c22q4dtzzqs5o2iygy435re
  spec varchar // "access-om2@git.2023.11.23=2023.11.23"
  spackversion varchar [ref: > spackversions.commit] // 6812713cf470b473a607f0de0e8e1cf53f804fb7
}

Table spackversions {
  commit varchar // "6812713cf470b473a607f0de0e8e1cf53f804fb7"
  version varchar // "0.20.3"
```

There is a related issue for the build infrastructure https://github.com/ACCESS-NRI/build-cd/issues/33

**Comment by aidanheerdegen** [comment]
This is related to https://github.com/ACCESS-NRI/build-cd/issues/33

**Comment by CodeGat** [comment]
What is the status of this ticket?

**Comment by aidanheerdegen** [comment]
> What is the status of this ticket?

It is a disgrace!

**Comment by CodeGat** [comment]
Closing as the associated issue is also closed. Note that in the final version of this, `created_at` and `release_url` are associated with the `modelbuilds` rather than the `componentbuilds`. Also `modelbuilds` and `componentbuilds` are many-to-many.
